### ISSUE TITLE
Doubt other type of plates

### ISSUE THREAD

**Issue by andressasousa** [ten-point-nine/freETarget#17]
![Screenshot_20210527-210327_Chrome](https://user-images.githubusercontent.com/83413905/119911258-5972dc80-bf2f-11eb-8eff-e5e70edba7d1.jpg)
![Screenshot_20210527-210308_Chrome](https://user-images.githubusercontent.com/83413905/119911265-5f68bd80-bf2f-11eb-9442-07a906d34cc9.jpg)
![Screenshot_20210527-210241_Chrome](https://user-images.githubusercontent.com/83413905/119911277-65f73500-bf2f-11eb-9a8d-82ba7c708f26.jpg)

Is it possible to use an Arduino Uno R3 SMD, a microcontroller board based on ATmega328, a Shield sensor Arduino 9 DOF? or in place of the Arduino 9 DOF Shield use a Ky038 Sound Sensor Module Arduino Microphone Sound Detector ?

**Comment by andressasousa** [comment]
Is it possible to use an Arduino Uno R3 SMD, an ATmega328 based microcontrolled board, an Arduino 9 DOF Shield sensor? or, in place of the Arduino 9 DOF Shield, use a Ky038 sound sensor module, Arduino microphone, sound detector?

**Comment by ten-point-nine** [comment]
Unfortunately no.

The Arduino typically samples around 40kHz for all channels.  This means that the four microphones would sample at 10kHz each.  

The freETarget samples at 8MHz per channel or 32MHz overall.  This is needed so as to resolve the position to well under 1mm which is what is needed for ISSF rules.

The freETarget board also supports the power supplies so that the pellet sound is picked up correctly.  The board also supplied the light and motor controls.

Allan

**Comment by andressasousa** [comment]
Could you enter the name of the sensors used and the Arduino?

So that I can check if you are in my country.

**Comment by ten-point-nine** [comment]
All of the information you need should be on GitHub already.

Look under the kicad folder 

Allan

**Comment by ten-point-nine** [comment]
A complete hardware set is available from me for $200+$25 shipping

Allan
