### ISSUE TITLE
PC Software upload failure

### ISSUE THREAD

**Issue by Moriniman** [ten-point-nine/freETarget#20]
I have a continual error msg when attempting to upload the Setup.exe for freETarget. 
![image](https://user-images.githubusercontent.com/62301897/128264871-7a0b44de-5acf-461d-8918-19a56d53e9a7.png)

**Comment by AzmodanRO** [comment]
looks like microsoft changed something to the redistributable file since publication.
best workaround is to manually download and install .NET Framework 4.7.2 - that way the setup will no longer try to download the prerequisite

https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-7-2-offline-installer-for-windows-05a72734-2127-a15d-50cf-daf56d5faec2

Azmo
